### ISSUE TITLE
dataset not accessible

### ISSUE THREAD

**Issue by utkarshaggarwal74** [GuanRunwei/FindVehicle#1]
given dataset, link address requires website log-in for accessing and downloading files.
Not able to create an account due to a mobile number format issue.
can you please provide another source to access the data-set!

**Comment by GuanRunwei** [comment]
> given dataset, link address requires website log-in for accessing and downloading files. Not able to create an account due to a mobile number format issue. can you please provide another source to access the data-set!

Hello, thank you for your issue. I have put the download link of Google Drive in the ReadMe file.

**Comment by utkarshaggarwal74** [comment]
thanks
